### ISSUE TITLE
Cannot place a custom code block on a page

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1061]
**Describe the bug**
When I try to place a custom code on some pages it does not work.

https://screencast-o-matic.com/watch/crflorVnu3V

I cant find anything that is specific it seems very random. Some page it will work and others like in the screen cast it will not.

**Comment by Gaganbird** [comment]
We were unable to duplicate the issue.

**Comment by scottw12** [comment]
So that means I am not telling the truth here lets just pass on it... you saw the screencast.

**Comment by Tychodewaard** [comment]
@scottw12 Can you try on a new page to put something basic like `<p>Testing 1 2</p>` ?
If that works as expected, I think the issue is that you injected javascript the first time. I have had issues with that in the past as well and I now put the scripts in the theme.js (which will also be minified if I am correct). 

Deleting the script and putting simple text in the same custom code block does not prove that the block doesn't work at all. The code is also in the json files where it is still able to mess things up. Hence, the suggestion to test fresh.

I use custom code blocks all the time but I don't add css or scripts in it.

**Comment by scottw12** [comment]
Thanks Tycho,  I normally do put all JavaScript in an external file but this script is one of those that has to go where it is displayed. The screen capture I sent was of a new page that had just been created to test the custom code block and it wouldn't work, but on this page it worked just fine https://dev.jcesba.org/events/bbq. I will look a bit deeper now that I have some ideas on where to look.

Again Thanks

**Comment by meetmandeep** [comment]
@scottw12 Can you save the page as template and provide us the exported file? Perhaps, we can use that to further investigate. 

To save as template:
Menu > Site > Pages> Page Menu > Save as Page Template > Specify a Name

Template can be found at \portals\PortalID\vThemes\Basic\templates\pages\templateName.json

**Comment by scottw12** [comment]
I think Tycho hit the nail on the head. The Custom Code block at this point is fairly useless as it is for code. You can't depend on it to work. If you do not have 100% correct code it crashes the entire system. It does not always occupy enough space to be visible on the page to edit.. Sometimes you cant even find it with the navigator. I had to delete my page and re-create it, and it works for now. I wouldn't even use it if I didn't have to place this JavaScript in a certain place on the page.

**Comment by meetmandeep** [comment]
@scottw12 Do you have any examples of bad code that's breaking the site?
