### ISSUE TITLE
Header / footer edits

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#350]
The logo is given a max-width:100px; 
Most of the time this is too small. Ideally the width is set in the UI. 

In the footer it is hardcoded that copyright is Vanjaro and 2020.
This should be editable like in the persona bar and [year]. If you change the copyright in the persona bar, it has no impact on Vanjaro. I suppose it would make sense if it is the same field in the db

**Comment by meetmandeep** [comment]
@Tychodewaard You can simply remove the max-width by clicking on the logo, click on styling tab and remove the Max Width. You have full control over the logo. 

> In the footer it is hardcoded that copyright is Vanjaro and 2020.
> This should be editable like in the persona bar and [year]. If you change the copyright in the persona bar, it has no impact on Vanjaro. I suppose it would make sense if it is the same field in the db

That's correct. Vanjaro (by design) does not use the copyright in persona bar. You could just as easily and visually change it in the footer so that paradigm doesn't make sense. Changing the copyright in a global block changes it on all pages. There is also no special tokens to manage the year at this time. 

I suppose we can use the DNN Tokens for current year but token replacement works on page level. We need to have a separate issue for that so we can discuss how to handle that.
