### ISSUE TITLE
EasyDNNNews not usable

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#411]
(Most/some?) third party extensions need a work around to be used. 
but EasyDNNNews can not be used at all as the 'manage' button can not be reached. 
I recorded my findings on https://www.youtube.com/watch?v=Lp3PyRSWsx8

**Comment by meetmandeep** [comment]
It looks like EasyDNNNews does not follow DNN conventions; it does not have any items in Action Menu until you click on any of the links within the module. 

Vanjaro, will disable all links and functionality in Edit Mode (for obvious reasons so you can click on content and make changes rather than navigate away). You can simply close the UX Manager and then click on any links as needed. 

However, EasyDNNNews disappears or hides the content if not in View Mode until the initial link is clicked. 

Please reach out to Easy DNN Solutions and ask them to make their modules compatible with Vanjaro. All they need to do is:

- Either show those links in Action Menu (Conventional Practices)
- Or show the links in View Mode also

For now, the workaround is to click the "Preview Icon" in UX Manager (Right next to Publish). This will open a new page where you will be able to click on the links.
