### ISSUE TITLE
Unable to Upload Logo via Logo & Site Icons Page

### ISSUE THREAD

**Issue by joshgk00** [vanjarosoftware/Vanjaro.Platform#62]
**Environment:**
Fresh install of DNN 9.7
Installed Vanjaro Beta Extension x64
Imported Default Vanjaro Page Template

**Issue**
I double-clicked on the Logo to upload a new file but the file doesn't upload. Here's a video
https://www.screencast.com/t/Ay7Cdp2HSkau

Using the Upload File in the main navigation seems to work fine.
https://www.screencast.com/t/Ay7Cdp2HSkau

**Comment by meetmandeep** [comment]
@joshgk00 This occurs since "webp" is not in your allowed host extensions. Behind the scences, Vanjaro automatically creates a webp version of the image when you upload for reduced size and performance. 

We're releasing a build soon that will automatically add webp to allowed host extensions. For now, you may add that extension manually if needed.

**Comment by joshgk00** [comment]
The webp extension does show up in Allowable File Extensions settings. 
https://www.screencast.com/t/mnVBnK3I

I also added it to IIS as a MIME type but still not able to upload
https://www.screencast.com/t/6BeiVapRvFK

**Comment by meetmandeep** [comment]
@joshgk00 Your image should be uploading but it's defaulting to images folder; regardless of which folder is selected. This bug was also logged last week and has been resolved. We'll push out a new release shortly.
